version: "3"
networks:
  ? sonarqube_net
services:
  postgresql:
    container_name: postgresql
    image: docker.io/postgres:10.13
    hostname: postgresql
    ports:
      - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    networks:
      -  sonarqube_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonarqube"]
      interval: 5s
      timeout: 5s
      retries: 5
  sonarqube:
    depends_on:
      postgresql:
        condition: service_healthy
    container_name: sonarqube
    image: localhost/sonarqube:latest
    hostname: sonarqube
    ports:
      - '9000:9000'
    environment:
      - SONARQUBE_DB_USER=sonarqube
      - SONARQUBE_DB_PASSWORD=sonarqube
      - SONARQUBE_DB_NAME=sonarqube
    networks:
      -  sonarqube_net
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        - SONARQUBE_VERSION=8.9.9.56886
