version: "3"
networks:
  ? sonarqube_net
services:
  postgresql:
    container_name: openshift-postgresql
    image: openshift-postgresql:1.0
    hostname: postgresql
    ports:
      - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      -  sonarqube_net
  sonarqube:
    container_name: openshift-sonarqube
    image: openshift-sonarqube:1.0
    hostname: sonarqube
    ports:
      - '9000:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=sonarqube
      - SONARQUBE_DATABASE_NAME=sonarqube
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_PASSWORD=sonarqube
    volumes:
      - sonarqube_data:/bitnami
    networks:
      -  sonarqube_net
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local